name: Publish to darimarsystem.com

on:
  push:
    branches: [ "main" ]

jobs:
  publish-darimar:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DarimarSystemWebsite\DarimarSystemWebsite.csproj --configuration Release --framework net8.0 --runtime win-x64 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false
    - uses: ./.github/actions/publish-darimar
      with:
        scripts-path: ${{ github.workspace }}\DarimarSystemWebsite\Scripts
        offline-path: ${{ github.workspace }}\DarimarSystemWebsite\Offline
        publish-path: ${{ github.workspace }}\DarimarSystemWebsite\bin\Release\net8.0\win-x64\publish
